pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('mathan2904')
        IMAGE_NAME = "mathan2904/simple-web-app"
        IMAGE_TAG = "latest"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat """
                    docker build -t %IMAGE_NAME%:%IMAGE_TAG% .
                """
            }
        }

        stage('Docker Login') {
            steps {
                bat """
                    echo %DOCKERHUB_PSW% | docker login -u %DOCKERHUB_USR% --password-stdin
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                bat """
                    docker push %IMAGE_NAME%:%IMAGE_TAG%
                """
            }
        }
    }

     post {
        success {
            mail to: "mathankumar29042004@gmail.com",
                 subject: "Build Success",
                 body: "The build was successful."
        }
        failure {
            mail to: "mathankumar29042004@gmail.com",
                 subject: "Build Failed",
                 body: "The build failed. Check logs."
        }
    }
}
