pipeline {
    agent any

    environment {
        IMAGE_NAME = "mathan2904/simple-web-app"
        IMAGE_TAG  = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'mathan2904',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    bat """
                        echo Building Docker Image...
                        docker build -t %IMAGE_NAME%:%IMAGE_TAG% .

                        echo Logging in to Docker Hub...
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin

                        echo Pushing image to Docker Hub...
                        docker push %IMAGE_NAME%:%IMAGE_TAG%
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline Completed"
        }
    }
}
